//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRMPNotifier.MRMPWCFService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="workerInformation", Namespace="http://schemas.datacontract.org/2004/07/MRMPService.WCF")]
    [System.SerializableAttribute()]
    public partial class workerInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int currentJobsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string versionNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string agentId {
            get {
                return this.agentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.agentIdField, value) != true)) {
                    this.agentIdField = value;
                    this.RaisePropertyChanged("agentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int currentJobs {
            get {
                return this.currentJobsField;
            }
            set {
                if ((this.currentJobsField.Equals(value) != true)) {
                    this.currentJobsField = value;
                    this.RaisePropertyChanged("currentJobs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string versionNumber {
            get {
                return this.versionNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.versionNumberField, value) != true)) {
                    this.versionNumberField = value;
                    this.RaisePropertyChanged("versionNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MRMPWCFService.IMRPWCFService")]
    public interface IMRPWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMRPWCFService/CollectionInformation", ReplyAction="http://tempuri.org/IMRPWCFService/CollectionInformationResponse")]
        MRMPNotifier.MRMPWCFService.workerInformation CollectionInformation();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMRPWCFServiceChannel : MRMPNotifier.MRMPWCFService.IMRPWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MRPWCFServiceClient : System.ServiceModel.ClientBase<MRMPNotifier.MRMPWCFService.IMRPWCFService>, MRMPNotifier.MRMPWCFService.IMRPWCFService {
        
        public MRPWCFServiceClient() {
        }
        
        public MRPWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MRPWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MRPWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MRPWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MRMPNotifier.MRMPWCFService.workerInformation CollectionInformation() {
            return base.Channel.CollectionInformation();
        }
    }
}
