// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>CladesWorkerService</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace CladesWorkerService.CaaS
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute("datacenters", Namespace = "urn:didata.com:api:cloud:types", IsNullable = false)]
    public partial class DatacenterListType
    {

        private List<DatacenterType> datacenterField;

        public DatacenterListType()
        {
            this.datacenterField = new List<DatacenterType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("datacenter")]
        public List<DatacenterType> datacenter
        {
            get
            {
                return this.datacenterField;
            }
            set
            {
                this.datacenterField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:didata.com:api:cloud:types", IsNullable = true)]
    public partial class DatacenterType
    {

        private string displayNameField;

        private string cityField;

        private string stateField;

        private string countryField;

        private string vpnUrlField;

        private string ftpsHostField;

        private NetworkingType networkingField;

        private HypervisorType hypervisorField;

        private BackupType backupField;

        private ConsoleAccessType consoleAccessField;

        private MonitoringType monitoringField;

        private string idField;

        private string typeField;

        public DatacenterType()
        {
            this.monitoringField = new MonitoringType();
            this.consoleAccessField = new ConsoleAccessType();
            this.backupField = new BackupType();
            this.hypervisorField = new HypervisorType();
            this.networkingField = new NetworkingType();
        }

        public string displayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }

        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        public string vpnUrl
        {
            get
            {
                return this.vpnUrlField;
            }
            set
            {
                this.vpnUrlField = value;
            }
        }

        public string ftpsHost
        {
            get
            {
                return this.ftpsHostField;
            }
            set
            {
                this.ftpsHostField = value;
            }
        }

        public NetworkingType networking
        {
            get
            {
                return this.networkingField;
            }
            set
            {
                this.networkingField = value;
            }
        }

        public HypervisorType hypervisor
        {
            get
            {
                return this.hypervisorField;
            }
            set
            {
                this.hypervisorField = value;
            }
        }

        public BackupType backup
        {
            get
            {
                return this.backupField;
            }
            set
            {
                this.backupField = value;
            }
        }

        public ConsoleAccessType consoleAccess
        {
            get
            {
                return this.consoleAccessField;
            }
            set
            {
                this.consoleAccessField = value;
            }
        }

        public MonitoringType monitoring
        {
            get
            {
                return this.monitoringField;
            }
            set
            {
                this.monitoringField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:didata.com:api:cloud:types", IsNullable = true)]
    public partial class NetworkingType
    {

        private List<PropertyType> propertyField;

        private string typeField;

        private string maintenanceStatusField;

        public NetworkingType()
        {
            this.propertyField = new List<PropertyType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("property")]
        public List<PropertyType> property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maintenanceStatus
        {
            get
            {
                return this.maintenanceStatusField;
            }
            set
            {
                this.maintenanceStatusField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:didata.com:api:cloud:types", IsNullable = true)]
    public partial class HypervisorType
    {

        private List<DiskSpeedType> diskSpeedField;

        private List<PropertyType> propertyField;

        private string typeField;

        private string maintenanceStatusField;

        public HypervisorType()
        {
            this.propertyField = new List<PropertyType>();
            this.diskSpeedField = new List<DiskSpeedType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("diskSpeed")]
        public List<DiskSpeedType> diskSpeed
        {
            get
            {
                return this.diskSpeedField;
            }
            set
            {
                this.diskSpeedField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("property")]
        public List<PropertyType> property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maintenanceStatus
        {
            get
            {
                return this.maintenanceStatusField;
            }
            set
            {
                this.maintenanceStatusField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:didata.com:api:cloud:types", IsNullable = true)]
    public partial class DiskSpeedType
    {

        private string displayNameField;

        private string abbreviationField;

        private string descriptionField;

        private string unavailableReasonField;

        private string idField;

        private bool defaultField;

        private bool availableField;

        public string displayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }

        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }

        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        public string unavailableReason
        {
            get
            {
                return this.unavailableReasonField;
            }
            set
            {
                this.unavailableReasonField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool @default
        {
            get
            {
                return this.defaultField;
            }
            set
            {
                this.defaultField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool available
        {
            get
            {
                return this.availableField;
            }
            set
            {
                this.availableField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:didata.com:api:cloud:types", IsNullable = true)]
    public partial class BackupType
    {

        private List<PropertyType> propertyField;

        private string typeField;

        private string maintenanceStatusField;

        public BackupType()
        {
            this.propertyField = new List<PropertyType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("property")]
        public List<PropertyType> property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maintenanceStatus
        {
            get
            {
                return this.maintenanceStatusField;
            }
            set
            {
                this.maintenanceStatusField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:didata.com:api:cloud:types", IsNullable = true)]
    public partial class ConsoleAccessType
    {

        private List<PropertyType> propertyField;

        private string maintenanceStatusField;

        public ConsoleAccessType()
        {
            this.propertyField = new List<PropertyType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("property")]
        public List<PropertyType> property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maintenanceStatus
        {
            get
            {
                return this.maintenanceStatusField;
            }
            set
            {
                this.maintenanceStatusField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:didata.com:api:cloud:types")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:didata.com:api:cloud:types", IsNullable = true)]
    public partial class MonitoringType
    {

        private List<PropertyType> propertyField;

        private string maintenanceStatusField;

        public MonitoringType()
        {
            this.propertyField = new List<PropertyType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("property")]
        public List<PropertyType> property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maintenanceStatus
        {
            get
            {
                return this.maintenanceStatusField;
            }
            set
            {
                this.maintenanceStatusField = value;
            }
        }
    }
}
