//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudMoveyWorkerService.CloudMoveyWorkerService.Sqlite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event : IEntity
    {
        public string id { get; set; }
        public string status { get; set; }
        public Nullable<int> severity { get; set; }
        public string component { get; set; }
        public string summary { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string entity { get; set; }
    }
}
