//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudMoveyWorkerService.CloudMoveyWorkerService.Sqlite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public string id { get; set; }
        public string name { get; set; }
        public string target { get; set; }
        public string initiator { get; set; }
        public string queued_for { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
    }
}
