//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudMoveyWorkerService.CloudMovey.Sqlite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Failovergroup
    {
        public string id { get; set; }
        public string parent_id { get; set; }
        public string group { get; set; }
        public Nullable<int> group_type { get; set; }
    }
}
